server:
  port: 7002
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user1:password1@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: cloud-consumer-order
#脱离eureka使用Ribbon
ribbon:
  eureka:
    enabled: false
cloud-provider-user:
  ribbon:
    listOfServers: localhost:7004
