server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://user1:password1@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: cloud-gateway-zuul
#zuul:
#  routes:
#    cloud-provider-user: /userProxy/**
#  ignored-services: cloud-consumer-order
# 或使用如下配置，同时可以做负载均衡
zuul:
  routes:
    user1:
      path: /userProxy/**
      serviceId: cloud-provider-user