server:
  port: 8763
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://user1:password1@localhost:8761/eureka
spring:
  application:
    name: cloud-hystrix-turbine
turbine:
  aggregator:
    clusterConfig: CLOUD-CONSUMER-ORDER
  appConfig: cloud-consumer-order