security:
  basic:
    enabled: true
  user:
    name: user1
    password: password1
server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user1:password1@localhost:8761/eureka